-- ABOUTME: Enables Row Level Security on all tables
-- ABOUTME: Blocks PostgREST access while allowing Prisma (service role) to work normally

-- Enable RLS on all tables
-- When RLS is enabled with no policies, it denies all access by default
-- The service role used by Prisma bypasses RLS automatically

ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Inquiry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GalleryPreference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HeroSlide" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PricingAddOn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HomepageContent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Testimonial" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ContractTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Gallery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientGallery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Contract" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChangeRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AvailabilitySlot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogPostCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogPostTag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogTag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PricingPackage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ContractUsageRight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UsageRight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PricingCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RetouchRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Service" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProcessStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InfoCard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceProcessStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceInfoCard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Image" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlogPostImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Faq" ENABLE ROW LEVEL SECURITY;
